apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: nationd18/commandservice:latest
#Cluster IP configuration. use --- o separate the deployment fro the cluster IP
#configuration
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  selector:
    app: commandservice
  ports:
  - name: commandservice
    protocol: TCP
    port: 80
    targetPort: 80
